#!/bin/bash
#PBS -l select=1:ncpus=16:mem=64gb:ngpus=1
#PBS -l walltime=6:00:00
#PBS -k oed
#PBS -j oe
source ~/.bashrc
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
echo "$SCRIPT_DIR"
cd ~/workspace/Time-LLM
conda activate allm4ts

nvidia-smi
#python -c 'import torch; print(torch.cuda.is_available())'

bash scripts/TimeLLM_M4_daily.sh
bash scripts/TimeLLM_M4_hourly.sh
bash scripts/TimeLLM_M4_weekly.sh

